In [14]:
import sqlite3

connection = sqlite3.connect(r'C:\Downloads\Telegram Desktop\test_database.db')

cursor = connection.cursor()

sql = "Create table Peoples(Firstname text, LastName text, Age int)"
query = "Insert into Peoples values ('Sardor','Ismatov', 23)"


# cursor.execute(sql)
cursor.execute(query)

connection.commit()
cursor.close()

connection.close()

In [15]:
import pyodbc


Driver_name = 'SQL Server'
Server_name = r'Sardors-laptop\SQLSERVER2025'
Database_Name = 'Movies'

connecting_string = f"DRIVER={{{Driver_name}}};SERVER={Server_name};DATABASE={Database_Name};Trusted_Connection=Yes;"

connection = pyodbc.connect(connecting_string)

cursor = connection.cursor()

query = "select  * from tblActor"

result = cursor.execute(query)
answer = result.fetchall()
row = answer
row

connection.commit()
connection.close()

row

[(1, 'Tom Cruise', datetime.datetime(1962, 7, 3, 9, 53, 21), 'Male'),
 (2, 'Sam Neill', datetime.datetime(1947, 9, 14, 0, 0), 'Male'),
 (3, 'Laura Dern', datetime.datetime(1967, 2, 10, 0, 0), 'Female'),
 (4, 'Jeff Goldblum', datetime.datetime(1952, 10, 22, 0, 0), 'Male'),
 (5, 'Richard Attenborough', datetime.datetime(1923, 8, 29, 0, 0), 'Male'),
 (6, 'Samuel L. Jackson', datetime.datetime(1948, 12, 21, 0, 0), 'Male'),
 (7, 'Tobey Maguire', datetime.datetime(1975, 6, 27, 0, 0), 'Male'),
 (8, 'Willem Dafoe', datetime.datetime(1955, 7, 22, 0, 0), 'Male'),
 (9, 'Kirsten Dunst', datetime.datetime(1982, 4, 30, 0, 0), 'Female'),
 (10, 'Naomi Watts', datetime.datetime(1968, 9, 28, 0, 0), 'Female'),
 (11, 'Jack Black', datetime.datetime(1969, 8, 28, 0, 0), 'Male'),
 (12, 'Adrien Brody', datetime.datetime(1973, 4, 14, 0, 0), 'Male'),
 (13, 'Andy Serkis', datetime.datetime(1964, 4, 20, 0, 0), 'Male'),
 (14, 'Brandon Routh', datetime.datetime(1979, 10, 9, 0, 0), 'Male'),
 (15, 'Kate Bosworth', datetime.datetime(1983, 1, 2, 0, 0), 'Female'),
 (16, 'Kevin Spacey', datetime.datetime(1959, 7, 26, 0, 0), 'Male'),
 (17, 'Leonardo DiCaprio', datetime.datetime(1974, 11, 11, 0, 0), 'Male'),
 (18, 'Kate Winslet', datetime.datetime(1975, 10, 5, 0, 0), 'Female'),
 (19, 'Billy Zane', datetime.datetime(1966, 2, 24, 0, 0), 'Male'),
 (20, 'Bill Paxton', datetime.datetime(1955, 5, 17, 0, 0), 'Male'),
 (21, 'Steve Carell', datetime.datetime(1962, 8, 16, 0, 0), 'Male'),
 (22, 'Morgan Freeman', datetime.datetime(1937, 6, 1, 0, 0), 'Male'),
 (23, 'Kevin Costner', datetime.datetime(1955, 1, 18, 0, 0), 'Male'),
 (24, 'Dennis Hopper', datetime.datetime(1936, 5, 17, 0, 0), 'Male'),
 (25, 'Ben Affleck', datetime.datetime(1972, 8, 15, 0, 0), 'Male'),
 (26, 'Josh Hartnett', datetime.datetime(1978, 7, 21, 0, 0), 'Male'),
 (27, 'Kate Beckinsale', datetime.datetime(1973, 7, 26, 0, 0), 'Female'),
 (28, 'Cuba Gooding Jr.', datetime.datetime(1968, 1, 2, 0, 0), 'Male'),
 (29, 'Jon Voight', datetime.datetime(1938, 12, 29, 0, 0), 'Male'),
 (30, 'Alec Baldwin', datetime.datetime(1958, 4, 3, 0, 0), 'Male'),
 (31, 'Tom Sizemore', datetime.datetime(1961, 11, 29, 0, 0), 'Male'),
 (32, 'Dan Aykroyd', datetime.datetime(1952, 7, 1, 0, 0), 'Male'),
 (33, 'Shia LaBeouf', datetime.datetime(1986, 6, 11, 0, 0), 'Male'),
 (34, 'John Turturro', datetime.datetime(1957, 2, 28, 0, 0), 'Male'),
 (35, 'Peter Cullen', datetime.datetime(1941, 7, 28, 0, 0), 'Male'),
 (36, 'Hugo Weaving', datetime.datetime(1960, 4, 4, 0, 0), 'Male'),
 (37, 'Megan Fox', datetime.datetime(1986, 5, 16, 0, 0), 'Female'),
 (38, 'Daniel Radcliffe', datetime.datetime(1989, 7, 23, 0, 0), 'Male'),
 (39, 'Ralph Fiennes', datetime.datetime(1962, 12, 22, 0, 0), 'Male'),
 (40, 'Brendan Gleeson', datetime.datetime(1955, 3, 29, 0, 0), 'Male'),
 (41, 'Gary Oldman', datetime.datetime(1958, 3, 21, 0, 0), 'Male'),
 (42, 'Michael Gambon', datetime.datetime(1940, 10, 19, 0, 0), 'Male'),
 (43, 'Alan Rickman', datetime.datetime(1946, 2, 21, 0, 0), 'Male'),
 (44, 'Emma Thompson', datetime.datetime(1959, 4, 15, 0, 0), 'Female'),
 (45, 'Helena Bonham Carter', datetime.datetime(1966, 5, 26, 0, 0), 'Female'),
 (46, 'Robbie Coltrane', datetime.datetime(1950, 3, 30, 0, 0), 'Male'),
 (47, 'Emma Watson', datetime.datetime(1990, 4, 15, 0, 0), 'Female'),
 (48, 'Rupert Grint', datetime.datetime(1988, 8, 24, 0, 0), 'Male'),
 (49, 'Robin Wright Penn', datetime.datetime(1966, 4, 8, 0, 0), 'Female'),
 (50, 'Anthony Hopkins', datetime.datetime(1937, 12, 31, 0, 0), 'Male'),
 (51, 'John Malkovich', datetime.datetime(1953, 12, 9, 0, 0), 'Male'),
 (52, 'Ray Winstone', datetime.datetime(1957, 2, 19, 0, 0), 'Male'),
 (53, 'Angelina Jolie', datetime.datetime(1975, 6, 4, 0, 0), 'Female'),
 (54, 'John Goodman', datetime.datetime(1952, 6, 20, 0, 0), 'Male'),
 (55, 'Jerry Seinfeld', datetime.datetime(1954, 4, 29, 0, 0), 'Male'),
 (56, 'Renee Zellweger', datetime.datetime(1969, 4, 25, 0, 0), 'Female'),
 (57, 'Matthew Broderick', datetime.datetime(1962, 3, 21, 0, 0), 'Male'),
 (58, 'Chris Rock', datetime.datetime(1965, 2, 7, 0, 0), 'Male'),
 (59, 'Ray Liotta', datetime.datetime(1954, 12, 18, 0, 0), 'Male'),
 (60, 'Rip Torn', datetime.datetime(1931, 2, 6, 0, 0), 'Male'),
 (61, 'Johnny Depp', datetime.datetime(1963, 6, 9, 0, 0), 'Male'),
 (62, 'Geoffrey Rush', datetime.datetime(1951, 7, 6, 0, 0), 'Male'),
 (63, 'Orlando Bloom', datetime.datetime(1977, 1, 13, 0, 0), 'Male'),
 (64, 'Keira Knightley', datetime.datetime(1985, 3, 26, 0, 0), 'Female'),
 (65, 'Bill Nighy', datetime.datetime(1949, 12, 12, 0, 0), 'Male'),
 (66, 'Jonathan Pryce', datetime.datetime(1947, 6, 1, 0, 0), 'Male'),
 (67, 'Stellan Skarsgard', datetime.datetime(1951, 6, 13, 0, 0), 'Male'),
 (68, 'Will Smith', datetime.datetime(1968, 9, 25, 0, 0), 'Male'),
 (69, 'Patton Oswalt', datetime.datetime(1969, 1, 27, 0, 0), 'Male'),
 (70, 'Ian Holm', datetime.datetime(1931, 9, 12, 0, 0), 'Male'),
 (71, 'Brian Dennehy', datetime.datetime(1938, 7, 9, 0, 0), 'Male'),
 (72, "Peter O'Toole", datetime.datetime(1932, 8, 2, 0, 0), 'Male'),
 (73, 'Brian Cox', datetime.datetime(1946, 6, 1, 0, 0), 'Male'),
 (75, 'Brad Pitt', datetime.datetime(1963, 12, 18, 0, 0), 'Male'),
 (76, 'Diane Kruger', datetime.datetime(1976, 7, 15, 0, 0), 'Female'),
 (77, 'Eric Bana', datetime.datetime(1968, 8, 9, 0, 0), 'Male'),
 (78, 'Christian Bale', datetime.datetime(1974, 1, 30, 0, 0), 'Male'),
 (79, 'Michael Caine', datetime.datetime(1933, 3, 14, 0, 0), 'Male'),
 (80, 'Liam Neeson', datetime.datetime(1952, 6, 7, 0, 0), 'Male'),
 (81, 'Katie Holmes', datetime.datetime(1978, 12, 18, 0, 0), 'Female'),
 (82, 'Rutger Hauer', datetime.datetime(1944, 1, 23, 0, 0), 'Male'),
 (83, 'Ken Watanabe', datetime.datetime(1959, 10, 21, 0, 0), 'Male'),
 (84, 'James Fox', datetime.datetime(1939, 5, 19, 0, 0), 'Male'),
 (85, 'Christopher Lee', datetime.datetime(1922, 5, 27, 0, 0), 'Male'),
 (86, 'Pierce Brosnan', datetime.datetime(1953, 5, 16, 0, 0), 'Male'),
 (87, 'Halle Berry', datetime.datetime(1966, 8, 14, 0, 0), 'Female'),
 (88, 'Rosamund Pike', datetime.datetime(1979, 1, 28, 0, 0), 'Female'),
 (89, 'Judi Dench', datetime.datetime(1934, 12, 9, 0, 0), 'Female'),
 (90, 'John Cleese', datetime.datetime(1939, 10, 27, 0, 0), 'Male'),
 (91, 'Michael Madsen', datetime.datetime(1958, 9, 25, 0, 0), 'Male'),
 (92, 'Samantha Bond', datetime.datetime(1961, 11, 27, 0, 0), 'Female'),
 (93, 'Mel Gibson', datetime.datetime(1956, 1, 3, 0, 0), 'Male'),
 (94, 'Danny Glover', datetime.datetime(1946, 7, 22, 0, 0), 'Male'),
 (95, 'Joe Pesci', datetime.datetime(1943, 2, 9, 0, 0), 'Male'),
 (96, 'Rene Russo', datetime.datetime(1954, 2, 17, 0, 0), 'Female'),
 (97, 'Jet Li', datetime.datetime(1963, 4, 26, 0, 0), 'Male'),
 (98, 'Bruce Willis', datetime.datetime(1955, 3, 19, 0, 0), 'Male'),
 (99, 'Billy Bob Thornton', datetime.datetime(1955, 8, 4, 0, 0), 'Male'),
 (100, 'Liv Tyler', datetime.datetime(1977, 7, 1, 0, 0), 'Female'),
 (101, 'Steve Buscemi', datetime.datetime(1957, 12, 13, 0, 0), 'Male'),
 (102, 'Owen Wilson', datetime.datetime(1968, 11, 18, 0, 0), 'Male'),
 (103, 'Michael Clarke Duncan', datetime.datetime(1957, 12, 10, 0, 0), 'Male'),
 (104, 'Peter Stormare', datetime.datetime(1953, 8, 27, 0, 0), 'Male'),
 (105, 'Tommy Lee Jones', datetime.datetime(1946, 9, 15, 0, 0), 'Male'),
 (106, 'Jamie Foxx', datetime.datetime(1967, 12, 13, 0, 0), 'Male'),
 (107, 'Jessica Biel', datetime.datetime(1982, 3, 3, 0, 0), 'Female'),
 (108, 'Ving Rhames', datetime.datetime(1959, 5, 12, 0, 0), 'Male'),
 (109, 'Donald Sutherland', datetime.datetime(1935, 7, 17, 0, 0), 'Male'),
 (110, 'James Woods', datetime.datetime(1947, 4, 18, 0, 0), 'Male'),
 (111, 'Colin Farrell', datetime.datetime(1976, 5, 31, 0, 0), 'Male'),
 (112, 'Ciaran Hinds', datetime.datetime(1953, 2, 9, 0, 0), 'Male'),
 (113, 'Sophie Marceau', datetime.datetime(1966, 11, 17, 0, 0), 'Female'),
 (114, 'Robert Carlyle', datetime.datetime(1961, 4, 14, 0, 0), 'Male'),
 (115, 'Denise Richards', datetime.datetime(1971, 2, 17, 0, 0), 'Female'),
 (116, 'Desmond Llewelyn', datetime.datetime(1913, 9, 12, 0, 0), 'Male'),
 (117, 'Russell Crowe', datetime.datetime(1964, 4, 7, 0, 0), 'Male'),
 (118, 'Paul Bettany', datetime.datetime(1971, 5, 27, 0, 0), 'Male'),
 (119, 'Dakota Fanning', datetime.datetime(1994, 2, 23, 0, 0), 'Female'),
 (120, 'Tim Robbins', datetime.datetime(1958, 10, 16, 0, 0), 'Male'),
 (121, 'Matt Damon', datetime.datetime(1970, 10, 8, 0, 0), 'Male'),
 (122, 'Julia Stiles', datetime.datetime(1981, 3, 28, 0, 0), 'Female'),
 (123, 'David Strathairn', datetime.datetime(1949, 1, 26, 0, 0), 'Male'),
 (124, 'Paddy Considine', datetime.datetime(1974, 9, 5, 0, 0), 'Male'),
 (125, 'Albert Finney', datetime.datetime(1936, 5, 9, 0, 0), 'Male'),
 (126, 'Monica Bellucci', datetime.datetime(1964, 9, 30, 0, 0), 'Female'),
 (127, 'Laurence Fishburne', datetime.datetime(1961, 7, 30, 0, 0), 'Male'),
 (128, 'Carrie-Anne Moss', datetime.datetime(1967, 8, 21, 0, 0), 'Female'),
 (129, 'Keanu Reeves', datetime.datetime(1964, 9, 2, 0, 0), 'Male'),
 (130, 'Tom Hanks', datetime.datetime(1956, 7, 9, 0, 0), 'Male'),
 (131, 'Audrey Tautou', datetime.datetime(1976, 8, 9, 0, 0), 'Female'),
 (132, 'Ian McKellen', datetime.datetime(1939, 5, 25, 0, 0), 'Male'),
 (133, 'Jean Reno', datetime.datetime(1948, 7, 30, 0, 0), 'Male'),
 (134, 'Jurgen Prochnow', datetime.datetime(1941, 6, 10, 0, 0), 'Male'),
 (135, 'Richard Harris', datetime.datetime(1930, 10, 1, 0, 0), 'Male'),
 (136, 'John Hurt', datetime.datetime(1940, 1, 22, 0, 0), 'Male'),
 (137, 'Dennis Quaid', datetime.datetime(1954, 4, 9, 0, 0), 'Male'),
 (138, 'Jake Gyllenhaal', datetime.datetime(1980, 12, 19, 0, 0), 'Male'),
 (139, 'Billy Connolly', datetime.datetime(1942, 11, 24, 0, 0), 'Male'),
 (140, 'Hiroyuki Sanada', datetime.datetime(1960, 10, 12, 0, 0), 'Male'),
 (141, 'Cillian Murphy', datetime.datetime(1976, 5, 25, 0, 0), 'Male'),
 (142, 'Michelle Yeoh', datetime.datetime(1962, 8, 6, 0, 0), 'Female'),
 (143, 'George Clooney', datetime.datetime(1961, 5, 6, 0, 0), 'Male'),
 (144, 'Mark Wahlberg', datetime.datetime(1971, 6, 5, 0, 0), 'Male'),
 (145, 'John C. Reilly', datetime.datetime(1965, 5, 24, 0, 0), 'Male'),
 (146, 'Mary Elizabeth Mastrantonio', datetime.datetime(1958, 11, 17, 0, 0), 'Female'),
 (147, 'Michael Ironside', datetime.datetime(1950, 2, 12, 0, 0), 'Male'),
 (148, 'Philip Seymour Hoffman', datetime.datetime(1967, 7, 23, 0, 0), 'Male'),
 (149, 'Michelle Monaghan', datetime.datetime(1976, 3, 23, 0, 0), 'Female'),
 (150, 'Simon Pegg', datetime.datetime(1970, 2, 14, 0, 0), 'Male'),
 (151, 'Nicolas Cage', datetime.datetime(1964, 1, 7, 0, 0), 'Male'),
 (152, 'Christian Slater', datetime.datetime(1969, 8, 18, 0, 0), 'Male'),
 (153, 'Ewan McGregor', datetime.datetime(1971, 3, 31, 0, 0), 'Male'),
 (154, 'Natalie Portman', datetime.datetime(1981, 6, 9, 0, 0), 'Female'),
 (155, 'Hayden Christensen', datetime.datetime(1981, 4, 19, 0, 0), 'Male'),
 (156, 'Frank Oz', datetime.datetime(1944, 5, 25, 0, 0), 'Male'),
 (157, 'Ian McDiarmid', datetime.datetime(1944, 8, 11, 0, 0), 'Male'),
 (158, 'Temuera Morrison', datetime.datetime(1960, 12, 26, 0, 0), 'Male'),
 (159, 'Rena Owen', datetime.datetime(1962, 7, 22, 0, 0), 'Female'),
 (160, 'Billy Crystal', datetime.datetime(1948, 3, 14, 0, 0), 'Male'),
 (161, 'James Coburn', datetime.datetime(1928, 8, 31, 0, 0), 'Male'),
 (162, 'Ray Park', datetime.datetime(1974, 8, 23, 0, 0), 'Male'),
 (163, 'Anthony Daniels', datetime.datetime(1946, 2, 21, 0, 0), 'Male'),
 (164, 'Kenny Baker', datetime.datetime(1934, 8, 24, 0, 0), 'Male'),
 (165, 'Peter Mayhew', datetime.datetime(1944, 5, 19, 0, 0), 'Male'),
 (166, 'Joe Don Baker', datetime.datetime(1936, 2, 12, 0, 0), 'Male'),
 (167, 'Elliott Gould', datetime.datetime(1938, 8, 29, 0, 0), 'Male'),
 (168, 'Andy Garcia', datetime.datetime(1956, 4, 12, 0, 0), 'Male'),
 (169, 'Julia Roberts', datetime.datetime(1967, 10, 28, 0, 0), 'Female'),
 (170, 'Don Cheadle', datetime.datetime(1964, 11, 29, 0, 0), 'Male'),
 (171, 'Timothy Olyphant', datetime.datetime(1968, 5, 20, 0, 0), 'Male'),
 (172, 'Jackie Chan', datetime.datetime(1954, 4, 7, 0, 0), 'Male'),
 (173, 'Steve Coogan', datetime.datetime(1965, 10, 14, 0, 0), 'Male'),
 (174, 'Arnold Schwarzenegger', datetime.datetime(1947, 7, 30, 0, 0), 'Male'),
 (175, 'Maggie Q', datetime.datetime(1979, 5, 22, 0, 0), 'Female'),
 (176, 'Sammo Hung', datetime.datetime(1952, 1, 7, 0, 0), 'Male'),
 (177, 'Jim Broadbent', datetime.datetime(1949, 5, 24, 0, 0), 'Male'),
 (178, 'Luke Wilson', datetime.datetime(1971, 9, 21, 0, 0), 'Male'),
 (179, 'Jeremy Irons', datetime.datetime(1948, 9, 19, 0, 0), 'Male'),
 (180, 'Edward Norton', datetime.datetime(1969, 8, 18, 0, 0), 'Male'),
 (181, 'Vince Vaughan', datetime.datetime(1970, 3, 28, 0, 0), 'Male'),
 (182, 'Cate Blanchett', datetime.datetime(1969, 5, 14, 0, 0), 'Female'),
 (183, 'Jude Law', datetime.datetime(1972, 12, 29, 0, 0), 'Male'),
 (184, 'Brent Spiner', datetime.datetime(1949, 2, 2, 0, 0), 'Male'),
 (185, 'Viggo Mortensen', datetime.datetime(1958, 10, 20, 0, 0), 'Male'),
 (186, 'Elijah Wood', datetime.datetime(1981, 1, 28, 0, 0), 'Male'),
 (187, 'James Cromwell', datetime.datetime(1940, 1, 27, 0, 0), 'Male'),
 (188, 'Bridget Moynahan', datetime.datetime(1971, 4, 28, 0, 0), 'Female'),
 (189, 'Daniel Craig', datetime.datetime(1968, 3, 2, 0, 0), 'Male'),
 (190, 'Max von Sydow', datetime.datetime(1929, 4, 10, 0, 0), 'Male'),
 (191, 'Linda Hamilton', datetime.datetime(1956, 9, 26, 0, 0), 'Female'),
 (192, 'Edward Furlong', datetime.datetime(1977, 8, 2, 0, 0), 'Male'),
 (193, 'Robert Patrick', datetime.datetime(1958, 11, 5, 0, 0), 'Male'),
 (194, 'Kenneth Branagh', datetime.datetime(1960, 12, 10, 0, 0), 'Male'),
 (195, 'Denzel Washington', datetime.datetime(1954, 12, 28, 0, 0), 'Male'),
 (196, 'Djimon Hounsou', datetime.datetime(1964, 4, 24, 0, 0), 'Male'),
 (197, 'Jennifer Connelly', datetime.datetime(1970, 12, 12, 0, 0), 'Female'),
 (198, 'Arnold Vosloo', datetime.datetime(1962, 6, 16, 0, 0), 'Male'),
 (199, 'Joaquin Phoenix', datetime.datetime(1974, 10, 28, 0, 0), 'Male'),
 (200, 'Connie Nielsen', datetime.datetime(1965, 7, 3, 0, 0), 'Female'),
 (201, 'Oliver Reed', datetime.datetime(1937, 2, 13, 0, 0), 'Male'),
 (202, 'Jamie Lee Curtis', datetime.datetime(1958, 11, 22, 0, 0), 'Female'),
 (203, 'Tom Arnold', datetime.datetime(1959, 3, 6, 0, 0), 'Male'),
 (204, 'Charlton Heston', datetime.datetime(1924, 10, 4, 0, 0), 'Male'),
 (205, 'Tia Carrere', datetime.datetime(1967, 1, 2, 0, 0), 'Female'),
 (206, 'Art Malik', datetime.datetime(1952, 11, 13, 0, 0), 'Male'),
 (207, 'Eliza Dushku', datetime.datetime(1980, 12, 30, 0, 0), 'Female'),
 (208, 'Daniel Day-Lewis', datetime.datetime(1957, 4, 29, 0, 0), 'Male'),
 (209, 'Cameron Diaz', datetime.datetime(1972, 8, 30, 0, 0), 'Female'),
 (210, 'Milla Jovovich', datetime.datetime(1975, 12, 17, 0, 0), 'Female'),
 (211, 'Chris Tucker', datetime.datetime(1972, 8, 31, 0, 0), 'Male'),
 (212, 'Sean Bean', datetime.datetime(1959, 4, 17, 0, 0), 'Male'),
 (213, 'Karl Urban', datetime.datetime(1972, 6, 7, 0, 0), 'Male'),
 (214, 'Linda Fiorentino', datetime.datetime(1958, 3, 9, 0, 0), 'Female'),
 (215, 'Jack Nicholson', datetime.datetime(1937, 4, 22, 0, 0), 'Male'),
 (216, 'Martin Sheen', datetime.datetime(1940, 8, 3, 0, 0), 'Male'),
 (217, 'Paul Giamatti', datetime.datetime(1967, 6, 6, 0, 0), 'Male'),
 (218, 'F. Murray Abraham', datetime.datetime(1939, 10, 24, 0, 0), 'Male'),
 (219, 'Charles Dance', datetime.datetime(1946, 10, 10, 0, 0), 'Male'),
 (221, 'Catherine Zeta-Jones', datetime.datetime(1969, 9, 25, 0, 0), 'Female'),
 (222, 'Adam Sandler', datetime.datetime(1966, 9, 9, 0, 0), 'Male'),
 (223, 'Christopher Walken', datetime.datetime(1943, 3, 31, 0, 0), 'Male'),
 (224, 'David Hasselhoff', datetime.datetime(1952, 7, 17, 0, 0), 'Male'),
 (225, 'Henry Winkler', datetime.datetime(1945, 10, 30, 0, 0), 'Male'),
 (226, 'Jim Carrey', datetime.datetime(1962, 1, 17, 0, 0), 'Male'),
 (227, 'Jennifer Aniston', datetime.datetime(1969, 2, 11, 0, 0), 'Female'),
 (228, 'Emmanuelle Beart', datetime.datetime(1963, 8, 14, 0, 0), 'Female'),
 (229, 'Robert Duvall', datetime.datetime(1931, 1, 5, 0, 0), 'Male'),
 (230, 'Tea Leoni', datetime.datetime(1966, 2, 25, 0, 0), 'Female'),
 (231, 'Jon Favreau', datetime.datetime(1966, 10, 19, 0, 0), 'Male'),
 (232, 'Vanessa Redgrave', datetime.datetime(1937, 1, 30, 0, 0), 'Female'),
 (233, 'Paul Newman', datetime.datetime(1925, 1, 26, 0, 0), 'Male'),
 (234, 'Stanley Tucci', datetime.datetime(1960, 11, 11, 0, 0), 'Male'),
 (235, 'Ed Harris', datetime.datetime(1950, 11, 28, 0, 0), 'Male'),
 (236, 'Christopher Plummer', datetime.datetime(1929, 12, 13, 0, 0), 'Male'),
 (237, 'Clive Owen', datetime.datetime(1964, 10, 3, 0, 0), 'Male'),
 (238, 'Bill Pullman', datetime.datetime(1953, 12, 17, 0, 0), 'Male'),
 (239, 'Mary McDonnell', datetime.datetime(1952, 4, 28, 0, 0), 'Female'),
 (240, 'Randy Quaid', datetime.datetime(1950, 10, 1, 0, 0), 'Male'),
 (241, 'Hugh Jackman', datetime.datetime(1968, 10, 12, 0, 0), 'Male'),
 (242, 'Patrick Stewart', datetime.datetime(1940, 7, 13, 0, 0), 'Male'),
 (243, 'Famke Janssen', datetime.datetime(1965, 11, 5, 0, 0), 'Female'),
 (244, 'Sean Connery', datetime.datetime(1930, 8, 25, 0, 0), 'Male'),
 (245, 'Michael Biehn', datetime.datetime(1956, 7, 31, 0, 0), 'Male'),
 (246, 'Rachel Weisz', datetime.datetime(1971, 3, 7, 0, 0), 'Female'),
 (247, 'Will Ferrell', datetime.datetime(1967, 7, 16, 0, 0), 'Male'),
 (248, 'Sacha Baron Cohen', datetime.datetime(1971, 10, 13, 0, 0), 'Male'),
 (249, 'Dan Castellaneta', datetime.datetime(1957, 5, 29, 0, 0), 'Male'),
 (250, 'Julie Kavner', datetime.datetime(1950, 9, 7, 0, 0), 'Female'),
 (251, 'Nancy Cartwright', datetime.datetime(1957, 10, 25, 0, 0), 'Female'),
 (252, 'Yeardley Smith', datetime.datetime(1964, 7, 3, 0, 0), 'Female'),
 (253, 'Patrick McGoohan', datetime.datetime(1928, 3, 19, 0, 0), 'Male'),
 (254, 'William Hurt', datetime.datetime(1950, 3, 20, 0, 0), 'Male'),
 (255, 'Sigourney Weaver', datetime.datetime(1949, 10, 8, 0, 0), 'Female'),
 (256, 'Mike Myers', datetime.datetime(1963, 5, 25, 0, 0), 'Male'),
 (257, 'Eddie Murphy', datetime.datetime(1961, 4, 3, 0, 0), 'Male'),
 (258, 'Antonio Banderas', datetime.datetime(1960, 8, 10, 0, 0), 'Male'),
 (259, 'Jonathan Frakes', datetime.datetime(1952, 8, 19, 0, 0), 'Male'),
 (260, 'LeVar Burton', datetime.datetime(1957, 2, 16, 0, 0), 'Male'),
 (261, 'Michael Dorn', datetime.datetime(1952, 12, 9, 0, 0), 'Male'),
 (262, 'Gates McFadden', datetime.datetime(1949, 3, 2, 0, 0), 'Female'),
 (263, 'Marina Sirtis', datetime.datetime(1955, 3, 29, 0, 0), 'Female'),
 (264, 'Bob Hoskins', datetime.datetime(1942, 10, 26, 0, 0), 'Male'),
 (265, 'Christopher Lloyd', datetime.datetime(1938, 10, 22, 0, 0), 'Male'),
 (266, 'Kathleen Turner', datetime.datetime(1954, 6, 19, 0, 0), 'Female'),
 (267, 'Christina Ricci', datetime.datetime(1980, 2, 12, 0, 0), 'Female'),
 (268, 'Vin Diesel', datetime.datetime(1967, 7, 18, 0, 0), 'Male'),
 (269, 'William Sadler', datetime.datetime(1950, 4, 13, 0, 0), 'Male'),
 (270, 'Bonnie Bedelia', datetime.datetime(1948, 3, 25, 0, 0), 'Female'),
 (271, 'Geena Davis', datetime.datetime(1956, 1, 21, 0, 0), 'Female'),
 (272, 'Kevin Bacon', datetime.datetime(1958, 7, 8, 0, 0), 'Male'),
 (273, 'Gary Sinise', datetime.datetime(1955, 3, 17, 0, 0), 'Male'),
 (274, 'Sharon Stone', datetime.datetime(1958, 3, 10, 0, 0), 'Female'),
 (275, 'Sylvester Stallone\r\nadvertisement', datetime.datetime(1946, 7, 6, 0, 0), 'Male'),
 (276, 'John Lithgow', datetime.datetime(1945, 10, 19, 0, 0), 'Male'),
 (277, 'Michael Rooker', datetime.datetime(1955, 4, 6, 0, 0), 'Male'),
 (278, 'Harrison Ford', datetime.datetime(1942, 7, 13, 0, 0), 'Male'),
 (279, 'Scarlett Johansson', datetime.datetime(1984, 11, 22, 0, 0), 'Female'),
 (280, 'Hilary Swank', datetime.datetime(1974, 7, 30, 0, 0), 'Female'),
 (281, 'Kathleen Quinlan', datetime.datetime(1954, 11, 19, 0, 0), 'Female'),
 (282, 'Joely Richardson', datetime.datetime(1965, 1, 9, 0, 0), 'Female'),

In [12]:
import pyodbc


Driver_name = 'SQL Server Native Client 11.0'
Server_name = r'Sardors-laptop\SQLSERVER2025'
Database_Name = 'Movies'

connecting_string = f"DRIVER={{{Driver_name}}};SERVER={Server_name};DATABASE={Database_Name};Trusted_Connection=Yes;"

connection = pyodbc.connect(connecting_string)

cursor = connection.cursor()

query = "select top 10 * from tblCountry"

result = cursor.execute(query)
answer = result.fetchall()
row = answer
row

connection.commit()
connection.close()

row

InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')

In [20]:
import pandas as pd
import sqlalchemy as sa

connection_string = 'mssql+pyodbc://Sardors-laptop\SQLSERVER2025/Movies?driver=SQL+Server'
engine = sa.create_engine(connection_string)
con = engine.connect()

df = pd.read_sql(sa.text('select filmid, filmname, filmreleasedate from tblfilm where filmid between 130 and 150'), con=con)
print(df)

    filmid                            filmname filmreleasedate
0      130                            Superman      1978-12-21
1      131                        Crimson Tide      1995-11-03
2      132                             Deja Vu      2006-12-15
3      133                         Man On Fire      2004-10-08
4      134                  Enemy of the State      1998-12-26
5      135                   Kill Bill: Vol. 1      2003-10-17
6      136                             Alien 3      1992-08-21
7      137                       Shanghai Noon      2000-08-25
8      138                   Kill Bill: Vol. 2      2004-04-23
9      139                            Blade II      2002-03-29
10     140                Flags of our Fathers      2006-12-22
11     141                              Casino      1996-02-23
12     142       Robin Hood: Prince of Thieves      1991-07-19
13     143                               Shrek      2001-06-29
14     144                    Shanghai Knights      2003-04-04
15     145  Indiana Jones and the Last Crusade      1989-06-30
16     146            Star Trek: First Contact      1996-12-13
17     147                               Blade      1998-11-13
18     148                       Patriot Games      1992-09-25
19     149                        The Fugitive      1993-09-24
20     150                        The Prestige      2006-11-10

<>:4: SyntaxWarning: invalid escape sequence '\S'
<>:4: SyntaxWarning: invalid escape sequence '\S'
W:\Users\sardo\AppData\Local\Temp\ipykernel_1344\82708318.py:4: SyntaxWarning: invalid escape sequence '\S'
  connection_string = 'mssql+pyodbc://Sardors-laptop\SQLSERVER2025/Movies?driver=SQL+Server'